#spring:
#  application:
#    name: calendar-service
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#server:
#  port: 8103
#
