### GET AUTHORIZATION CODE

GET http://localhost:9000/oauth2/authorize
    ?response_type=code
    &client_id=client
    &redirect_uri=http://localhost:8080/callback
    &scope=read
    &state=xyz123

### GET ACCESS TOKEN

POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic b2lkYy1jbGllbnQ6c2VjcmV0


###
POST http://localhost:8101/api/v1/profiles
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "johndoe@gmail.com",
  "username": "johndoe",
  "password": "johnandjane",
  "telegramId": ""
}


### GREETING
GET localhost:8101/greeting
Authorization: Bearer eyJraWQiOiJhMzVkZjcxNy01YWU2LTQxMzktOTVjNi0xOWRiNmRhNjM5NTAiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoib2lkYy1jbGllbnQiLCJuYmYiOjE3NTM1MTE2OTksInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiXSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTc1MzUxMzQ5OSwidmlwIjoic29uIiwiaWF0IjoxNzUzNTExNjk5LCJqdGkiOiIxYTNmOTVjZi1lNTJjLTQ2N2YtYjBmYi02NzQ5OGY2M2M1M2MifQ.ANhXg8-BDmvLp09UHgKnboSQQZWt5kJHRO4V5MmhfqjpylzLrg5eHw17BoT_Z2a6pxD2Na_y1VSFC6vc3e8epIIwmFX45CK23ng9N7gKLSMbGrtnKd5JUyvL1UdETOn60Az36XDke9WqRdHf9kzJhRP3dxwcKDJ13WqfF3i8qlzFdTqJqyhLIwvoW1Cx2b4Zr6S6nku3Naf_9Oqz3IlVa2yUEMtf3M80XB3toEJ-zxr7yUGrqvLNMZupUvcP0Tu3Ti85Vjag30zClNccRCT5khnNwUwbtsQvzMs-xMEFz9BluUHHRwFbhY8e-7-0Gypd8j2JzZ3_zR9e-dKzcTOjxg